### ISSUE TITLE
Hw06 part b Major_axis problems

### ISSUE THREAD

**Issue by Mr153759** [gabd-students/beardslee_jordan#3]
So far everything has been going fine on Hw06 part b but when i got to the major_axis <- sma(log_mass ~ log_tarsus, data = feathers) portion I got this message. Error in model.frame.default(formula = log_mass ~ log_tarsus, data = feathers, : invalid type (list) for variable 'log_mass'. I've tried writing the feathers file different ways, I've tried putting it in quotations, but nothing seems to fix it. What should i do?

**Comment by mtaylor-semo** [comment]
Hi Jordan,


The key part of the error message (I think) is "invalid type (list) for variable 'log_mass'". The sma function is expecting a vector but you are passing it a list. That suggests that you might not have log-transformed your data correctly.  You can take a look back at that to see if you can figure it out, or send me your code for the part leading up to the sma function? It will be in the "mutate(...)" part of your code.


Mike
--
Dr. Michael S. Taylor
Professor of Biology

Dept. of Biology, MS 6200

Southeast Missouri State University
Cape Girardeau, MO 63701

mtaylor@semo.edu<mailto:mtaylor@semo.edu>
(573) 651-2357
Rhodes 217
________________________________

**Comment by Mr153759** [comment]
Ok thank you, i will take a look and see if i can figure it out.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Mr153759** [comment]
Still nothing. I've ran my code several times and it seems ok up until it gets to the major_axis part. Here is the code i used, and I've pushed the entire thing through if you need that instead.

log_mass <- mutate(feathers, log(mass))

log_tarsus <- mutate(feathers, log(tarsus))

**Comment by mtaylor-semo** [comment]
The problems is that you did assigned `log(mass)` and `log(tarsus)` to variable names outside of your tibble (data frame). When you use `sma(log_mass ~ log_tarsus, data = feathers)`, you are telling the sma function to look for ALL data inside your tibble. What you want to do is:


feathers <- mutate(feathers, log_mass = log(mass)).


Notice how the result of `log(mass)` is assigned to `log_mass`. You would do the same thing for tarsus. You can do this in a single pipe:


feathers <- feathers %>%

  mutate(log_mass = log(mass),

                log_tarsus = log(tarsus))


That will create two new columns in your tibble, ready for use by the `sma()` function.

Mike
--
Dr. Michael S. Taylor
Professor of Biology

Dept. of Biology, MS 6200

Southeast Missouri State University
Cape Girardeau, MO 63701

mtaylor@semo.edu<mailto:mtaylor@semo.edu>
(573) 651-2357
Rhodes 217
________________________________

**Comment by Mr153759** [comment]
That did it, thank you for all your help.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
